### ISSUE TITLE
2023.10.10 Not working

### ISSUE THREAD

**Issue by Crashman1983** [BenPru/luxtronik#144]
After update from 2023.09.21 Enties were not available. Deinstalled Integration and installed again, but same problem. 

<img width="1100" alt="image" src="https://github.com/BenPru/luxtronik/assets/4194672/595b329a-326c-4476-8682-576c33dbb78c">

```
Logger: homeassistant.config_entries
Source: config_entries.py:441
First occurred: 10:52:13 (3 occurrences)
Last logged: 11:07:15

Config entry 'None None 310312-0495' for luxtronik2 integration not ready yet: Read: Error communicating with device; Retrying in background
```

```
`Logger: custom_components.luxtronik2
Source: custom_components/luxtronik2/lux_helper.py:148
Integration: Luxtronik
First occurred: 10:52:13 (42 occurrences)
Last logged: 11:09:21

Unexpected exception when checking if a socket is closed
Traceback (most recent call last):
  File "/config/custom_components/luxtronik2/lux_helper.py", line 148, in _is_socket_closed
    data = sock.recv(16, socket.MSG_DONTWAIT | socket.MSG_PEEK)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: timed out`
```

**Comment by 02curls** [comment]
the same problem here, and downgrading not helping

**Comment by Crashman1983** [comment]
After setting back the change within lux_helper.py integration is working again.

**Comment by BenPru** [comment]
Okay. Can you connect your heatpump on the local network with a mobile app? (e.g. Luxprobe)
No --> Please restart your heatpump and try again. If it doesn't work after that please check your heatpump network config.
---
Yes --> Please provide a logfile in this ticket with your heatpump firmware version, ja version and luxtronik integration version.

**Comment by Crashman1983** [comment]
I checked that. When my Heatpump was not working in HA, it did well using Webinterface or Alpha Control App.

**Comment by BenPru** [comment]
> I checked that. When my Heatpump was not working in HA, it did well using Webinterface or Alpha Control App.

Does the main branch work for you?
If not, please provide a log file and the versions.

**Comment by Crashman1983** [comment]
Downloaded main, restart --> not working

Logger: homeassistant.config_entries
Source: config_entries.py:441
First occurred: 20:38:40 (2 occurrences)
Last logged: 20:38:51

Config entry 'None None 310312-0495' for luxtronik2 integration not ready yet: Read: Error communicating with device; Retrying in background
Config entry 'Default' for unifi integration not ready yet; Retrying in background


Logger: custom_components.luxtronik2
Source: custom_components/luxtronik2/lux_helper.py:148
Integration: Luxtronik
First occurred: 20:38:40 (5 occurrences)
Last logged: 20:39:32

Unexpected exception when checking if a socket is closed
Traceback (most recent call last):
  File "/config/custom_components/luxtronik2/lux_helper.py", line 148, in _is_socket_closed
    data = sock.recv(16, socket.MSG_DONTWAIT | socket.MSG_PEEK)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: timed out

**Comment by BenPru** [comment]
> But setting True to False does also work in main ;)

[See](https://github.com/BenPru/luxtronik/commit/dd2c968d9080ba5a0fe02530a6ab8714e41635f5#diff-ed6df6d96cb3b4171bbc48162af3117b5cde26c3f61ec8bf1c2da90637b74de8L159)
Main is changed from True to False...
Did you really updated to main?

**Comment by Crashman1983** [comment]
Reloaded from HACS, chose main and rebooted. I will double check.

**Comment by Crashman1983** [comment]
did again. I can confirm it is working.

**Comment by BenPru** [comment]
Please try [2023.10.11-Beta](https://github.com/BenPru/luxtronik/releases/tag/2023.10.11-Beta) and check that all is fixed finally.
Thank you for your input and tests.

**Comment by WaelderKrut** [comment]
**Main** is not working for me as well. Using Novelan LAV heatpump with firmware V3.89.1
![image](https://github.com/BenPru/luxtronik/assets/126291019/c13cf3eb-6443-4a1f-9ca5-c9aa86b61af7)
2023-10-11 21:35:57.501 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Novelan LAV12 - HV12 for luxtronik2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 399, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/luxtronik2/__init__.py", line 34, in async_setup_entry
    coordinator = LuxtronikCoordinator.connect(hass, entry)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/luxtronik2/coordinator.py", line 197, in connect
    timeout = config[CONF_TIMEOUT]
              ~~~~~~^^^^^^^^^^^^^^
KeyError: 'timeout'


**2023.10.9 is stable.** 


**2023.10.10 is not working**
![image](https://github.com/BenPru/luxtronik/assets/126291019/3541859c-ff73-4829-9ca9-f45536b91977)
2023-10-11 21:24:58.012 ERROR (MainThread) [custom_components.luxtronik2] Unexpected exception when checking if a socket is closed
Traceback (most recent call last):
  File "/config/custom_components/luxtronik2/lux_helper.py", line 148, in _is_socket_closed
    data = sock.recv(16, socket.MSG_DONTWAIT | socket.MSG_PEEK)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


**2023.10.11 not working**
![image](https://github.com/BenPru/luxtronik/assets/126291019/63fee1b8-5a2e-4041-8c44-0f12daa2c68a)
2023-10-11 21:32:50.516 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Novelan LAV12 - HV12 for luxtronik2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 399, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/luxtronik2/__init__.py", line 34, in async_setup_entry
    coordinator = LuxtronikCoordinator.connect(hass, entry)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/luxtronik2/coordinator.py", line 197, in connect
    timeout = config[CONF_TIMEOUT]
              ~~~~~~^^^^^^^^^^^^^^
KeyError: 'timeout'

**Comment by qubabos** [comment]
> **Main** is not working for me as well. Using Novelan LAV heatpump with firmware V3.89.1 ![image](https://user-images.githubusercontent.com/126291019/274396575-c13cf3eb-6443-4a1f-9ca5-c9aa86b61af7.png) 2023-10-11 21:35:57.501 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Novelan LAV12 - HV12 for luxtronik2 Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/config_entries.py", line 399, in async_setup result = await component.async_setup_entry(hass, self) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/luxtronik2/**init**.py", line 34, in async_setup_entry coordinator = LuxtronikCoordinator.connect(hass, entry) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/luxtronik2/coordinator.py", line 197, in connect timeout = config[CONF_TIMEOUT] ~~~~~~^^^^^^^^^^^^^^ KeyError: 'timeout'
> 
> **2023.10.9 is stable.**
> 
> **2023.10.10 is not working** ![image](https://user-images.githubusercontent.com/126291019/274396994-3541859c-ff73-4829-9ca9-f45536b91977.png) 2023-10-11 21:24:58.012 ERROR (MainThread) [custom_components.luxtronik2] Unexpected exception when checking if a socket is closed Traceback (most recent call last): File "/config/custom_components/luxtronik2/lux_helper.py", line 148, in _is_socket_closed data = sock.recv(16, socket.MSG_DONTWAIT | socket.MSG_PEEK) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> **2023.10.11 not working** ![image](https://user-images.githubusercontent.com/126291019/274397112-63fee1b8-5a2e-4041-8c44-0f12daa2c68a.png) 2023-10-11 21:32:50.516 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Novelan LAV12 - HV12 for luxtronik2 Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/config_entries.py", line 399, in async_setup result = await component.async_setup_entry(hass, self) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/luxtronik2/**init**.py", line 34, in async_setup_entry coordinator = LuxtronikCoordinator.connect(hass, entry) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/luxtronik2/coordinator.py", line 197, in connect timeout = config[CONF_TIMEOUT] ~~~~~~^^^^^^^^^^^^^^ KeyError: 'timeout'

exactly the same for me - aplha innotec V3.89.1

**Comment by Crashman1983** [comment]
2023.10.11 beta is not working for me. 

```
Logger: homeassistant.config_entries
Source: config_entries.py:399
First occurred: 11. Oktober 2023 um 21:47:27 (1 occurrences)
Last logged: 11. Oktober 2023 um 21:47:27

Error setting up entry None None 310312-0495 for luxtronik2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 399, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/luxtronik2/__init__.py", line 34, in async_setup_entry
    coordinator = LuxtronikCoordinator.connect(hass, entry)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/luxtronik2/coordinator.py", line 197, in connect
    timeout = config[CONF_TIMEOUT]
              ~~~~~~^^^^^^^^^^^^^^
KeyError: 'timeout'
```


```
Logger: custom_components.luxtronik2
Source: custom_components/luxtronik2/config_flow.py:269
Integration: Luxtronik
First occurred: 11. Oktober 2023 um 22:49:57 (1 occurrences)
Last logged: 11. Oktober 2023 um 22:49:57

Could not handle config_flow.async_step_dhcp DhcpServiceInfo(ip='xxx.xxx.xxx.xxx', hostname='', macaddress='yyyyyyyyyyy')
Traceback (most recent call last):
  File "/config/custom_components/luxtronik2/config_flow.py", line 269, in async_step_dhcp
    self._abort_if_unique_id_configured()
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1589, in _abort_if_unique_id_configured
    raise data_entry_flow.AbortFlow(error)
homeassistant.data_entry_flow.AbortFlow: Flow aborted: already_configured
```

**Comment by Crashman1983** [comment]
.12 is working after I deleted devices and did a fresh config flow

**Comment by qubabos** [comment]
> .12 is working after I deleted devices and did a fresh config flow

outdoor_temperature_average working for you ?

**Comment by Crashman1983** [comment]
Some new problems arrived with .12

<img width="487" alt="image" src="https://github.com/BenPru/luxtronik/assets/4194672/6ed37e54-91cd-44ab-8b03-e4510c60dc47">

```
Logger: homeassistant.setup
Source: setup.py:359
First occurred: 08:17:34 (2 occurrences)
Last logged: 08:17:34

Unable to prepare setup for platform luxtronik2.water_heater: Platform not found (Exception importing custom_components.luxtronik2.water_heater).
Unable to prepare setup for platform luxtronik2.climate: Platform not found (Exception importing custom_components.luxtronik2.climate).


```

- Logger: homeassistant.loader
- Source: loader.py:838
- First occurred: 08:17:34 (1 occurrences)
- Last logged: 08:17:34
- 
- Unexpected exception importing platform custom_components.luxtronik2.water_heater
- Traceback (most recent call last):
-   File "/usr/src/homeassistant/homeassistant/loader.py", line 838, in get_platform
-     cache[full_name] = self._import_platform(platform_name)
-                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
-   File "/usr/src/homeassistant/homeassistant/loader.py", line 855, in _import_platform
-     return importlib.import_module(f"{self.pkg_path}.{platform_name}")
-            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
-   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
-     return _bootstrap._gcd_import(name[level:], package, level)
-            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
-   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
-   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
-   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
-   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
-   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
-   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
-   File "/config/custom_components/luxtronik2/water_heater.py", line 52, in <module>
-     LuxtronikWaterHeaterDescription(
- TypeError: LuxtronikWaterHeaterDescription.__init__() got an unexpected keyword argument 'temperature_unit'
-

**Comment by Crashman1983** [comment]
```
Logger: homeassistant.config_entries
Source: config_entries.py:565
First occurred: 08:25:36 (2 occurrences)
Last logged: 08:25:36

Error unloading entry None None 310312-0495 for water_heater
Error unloading entry None None 310312-0495 for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 565, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py", line 156, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 202, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!

```

**Comment by qubabos** [comment]
> Some new problems arrived with .12
> 
> <img alt="image" width="487" src="https://user-images.githubusercontent.com/4194672/274500242-6ed37e54-91cd-44ab-8b03-e4510c60dc47.png">
> ```
> ```
same here :
![1234](https://github.com/BenPru/luxtronik/assets/2496350/2b2a869f-c8d4-4dbb-9e61-9c0b487c310f)
also after couple of minutes temp reading gone wrong - see this flat line:
![123](https://github.com/BenPru/luxtronik/assets/2496350/a92e3890-e8ca-453e-8542-c24c08767aa5)

**Comment by Crashman1983** [comment]
Entity average outdoor temperature is deactivated by default, but working when activated manually

**Comment by qubabos** [comment]
there is no disabled entity to activate manually for me

**Comment by rhammen** [comment]
> Some new problems arrived with .12
> <img alt="image" width="487" src="https://user-images.githubusercontent.com/4194672/274500242-6ed37e54-91cd-44ab-8b03-e4510c60dc47.png">
> 
> ```
> Logger: homeassistant.setup
> Source: setup.py:359
> First occurred: 08:17:34 (2 occurrences)
> Last logged: 08:17:34
> 
> Unable to prepare setup for platform luxtronik2.water_heater: Platform not found (Exception importing custom_components.luxtronik2.water_heater).
> Unable to prepare setup for platform luxtronik2.climate: Platform not found (Exception importing custom_components.luxtronik2.climate).
> ```
> 
> ```
>  Logger: homeassistant.loader
> Source: loader.py:838
> First occurred: 08:17:34 (1 occurrences)
> Last logged: 08:17:34 
> 
> Unexpected exception importing platform custom_components.luxtronik2.water_heater
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/loader.py", line 838, in get_platform
>  cache[full_name] = self._import_platform(platform_name)
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/src/homeassistant/homeassistant/loader.py", line 855, in _import_platform
>  return importlib.import_module(f"{self.pkg_path}.{platform_name}")
>  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
>  return _bootstrap._gcd_import(name[level:], package, level)
>  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
> File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
> File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
> File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
> File "<frozen importlib._bootstrap_external>", line 940, in exec_module
> File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
> File "/config/custom_components/luxtronik2/water_heater.py", line 52, in <module>
>   LuxtronikWaterHeaterDescription(
> TypeError: LuxtronikWaterHeaterDescription.__init__() got an unexpected keyword argument 'temperature_unit'
>  
> ```

See #149, will be fixed with #150

**Comment by rhammen** [comment]
> there is no disabled entity to activate manually for me

I do have the Avg. Outdoor temperature sensor.

Settings-->Devices & Services.
Select Luxtronik integration, then select Devices, then select HP 
There I see the sensor "Avg. outdoor temperature"

In History, I can add the sensor "sensor.luxtronik2_outdoor_temperature_average"

**Comment by rhammen** [comment]
> Please try [2023.10.11-Beta](https://github.com/BenPru/luxtronik/releases/tag/2023.10.11-Beta) and check that all is fixed finally. Thank you for your input and tests.

After I fixed the "TypeError: LuxtronikWaterHeaterDescription.__init__() got an unexpected keyword argument 'temperature_unit'" problem (#149, fixed with #150), my setup works OK and I do not see the connection problems mentioned in this issue anymore.
So as far as I can tell, this problem looks fixed. Thanks!

**Comment by qubabos** [comment]
> > there is no disabled entity to activate manually for me
> 
> I do have the Avg. Outdoor temperature sensor.
> 
> Settings-->Devices & Services. Select Luxtronik integration, then select Devices, then select HP There I see the sensor "Avg. outdoor temperature"
> 
> In History, I can add the sensor "sensor.luxtronik2_outdoor_temperature_average"

its gone for me since update to 2023.10.10. there is completly no entity for this.
![Bez nazwy](https://github.com/BenPru/luxtronik/assets/2496350/ce0aafb0-991d-479a-959c-7c5d9f0d8c64)
no changes after upgrade to 2023.10.13 Beta

**Comment by Crashman1983** [comment]
2023.10.13-Beta is running fine. No more connection problems, no errors in log.
